[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[cibuildwheel.linux]
before-all = "sudo apt install python3-dev"

[cibuildwheel.macos]
before-all = "xcode-select --install"
